---
title: "Soil property mapping"
author: "Alex Koiter"
---

## Load libraries

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(terra)
  library(patchwork)
  library(sf)
})
```

## Load data

```{r}
ag_data <- read_csv(here::here("./notebooks/ag_terrain_data.csv"), show_col_types = FALSE) 
  # select("x", "y", "elevation", "ca", "mo", "u", "a_col", "h_col", "c_col", "organic", "ssa")

forest_data <- read_csv(here::here("./notebooks/forest_terrain_data.csv"), show_col_types = FALSE) 
  # select("x", "y", "elevation", "li", "nb", "zn", "v_col", "l_col")
```

## Agricultural soil properties
### Geochemisty and colour

```{r}

ag_rast <- rast(ag_data)
crs(x = ag_rast, warn=FALSE) <- "epsg:26914"

coords <- read_csv(here::here("./notebooks/coords.csv"), show_col_types = FALSE) %>% 
  st_as_sf(coords = c("long", "lat"),  crs = 4326) %>%
  st_transform(crs = 26914)

theme_right <-  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "right",
        legend.box.spacing = unit(0, "pt"),
        legend.margin=margin(0,0,0,3),
        legend.justification="left",
        legend.title = element_text(hjust = 0))
theme_left <-  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "left",
        legend.text.position = "left",
        legend.box.spacing = unit(0, "pt"),
        legend.margin=margin(0,3,0,0),
        legend.justification="right",
        legend.title = element_text(hjust = 1))

a_col <- ggplot() +
  tidyterra::geom_spatraster(data = ag_rast, aes(fill = a_col)) +
  scale_fill_viridis_c(name = bquote(italic("a*")), breaks = seq(2.5, 4, 0.5)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

c_col <- ggplot() +
  tidyterra::geom_spatraster(data = ag_rast, aes(fill = c_col)) +
  scale_fill_viridis_c(name = bquote(italic("c*")), breaks = seq(7, 11, 1)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) + 
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

h_col <- ggplot() +
  tidyterra::geom_spatraster(data = ag_rast, aes(fill = h_col)) +
  scale_fill_viridis_c(name = bquote(italic("h*")), breaks = seq(1.15, 1.25, 0.02)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) 

ca <- ggplot() +
  tidyterra::geom_spatraster(data = ag_rast, aes(fill = ca)) +
  scale_fill_viridis_c(name = "Ca", limits = c(1, 9.2), breaks = seq(1, 9, 2)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_right +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) 

mo <- ggplot() +
  tidyterra::geom_spatraster(data = ag_rast, aes(fill = mo)) +
  scale_fill_viridis_c(name = "Mo", breaks = seq(0.5, 2, 0.5)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_right +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) 

u <- ggplot() +
  tidyterra::geom_spatraster(data = ag_rast, aes(fill = u)) +
  scale_fill_viridis_c(name = "U", breaks = seq(1.2, 1.8, 0.2)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_right +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))
```

```{r}
#| fig-width: 12
#| fig-asp: 0.8
#| label: fig-ag_map
#| fig-cap: Kriged map of select colour (*a\**, *c\**, *h\**) and geochemical (Ca, Mo, U) properties across the agricultural site.
 
a_col + ca + c_col + mo + h_col + u + 
  plot_layout(ncol = 2) 
```

### Grain size, OM, elevation

```{r}

dem <- ggplot() +
  tidyterra::geom_spatraster(data = ag_rast, aes(fill = elevation)) +
  scale_fill_viridis_c(name = "Elevation", option = "inferno", limits = c(309, 312)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

ssa <- ggplot() +
  tidyterra::geom_spatraster(data = ag_rast, aes(fill = ssa)) +
  scale_fill_viridis_c(name = "SSA") +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_right +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

organic <- ggplot() +
  tidyterra::geom_spatraster(data = ag_rast, aes(fill = organic)) +
  scale_fill_viridis_c(name = "Organic") +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

scale_p <- ggplot() +
  geom_sf(data = filter(coords, site == "Agriculture"), colour = "white") +
  theme_void(base_size = 12)+
  ggspatial::annotation_scale(location = "bl", width_hint = 0.4) +
  ggspatial::annotation_north_arrow(location = "bl", pad_y  = unit(2, "cm"))

```

```{r}
#| fig-width: 12
#| fig-asp: 0.6
#| label: fig-ag_map2
#| fig-cap: Kriged map of organic matter content (%), specific surface area (m<sup>2</sup> kg<sup>-1</sup>), and elevation (m) across the agricultural site.

organic + ssa + dem + scale_p + 
  plot_layout(ncol = 2) 
```

## Agricultural soil properties
### Geochemisty and colour

```{r}

forest_rast <- rast(forest_data)
crs(x = forest_rast, warn=FALSE) <- "epsg:26914"

h_col_forest <- ggplot() +
  tidyterra::geom_spatraster(data = forest_rast, aes(fill = h_col)) +
  scale_fill_viridis_c(name = bquote(italic("h*")), limits =c(1.05, 1.25), breaks = seq(1.05, 1.25, 0.1)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

l_col <- ggplot() +
  tidyterra::geom_spatraster(data = forest_rast, aes(fill = l_col)) +
  scale_fill_viridis_c(name = bquote(italic("L")), limits =c(34, 60), breaks = seq(35, 60, 10)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) + 
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

v_col <- ggplot() +
  tidyterra::geom_spatraster(data = forest_rast, aes(fill = v_col)) +
  scale_fill_viridis_c(name = bquote(italic("v*")), breaks = seq(2, 7, 1)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) 

nb <- ggplot() +
  tidyterra::geom_spatraster(data = forest_rast, aes(fill = nb)) +
  scale_fill_viridis_c(name = "Nb", breaks = seq(0.25, 0.5, 0.05)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_right +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) 

li <- ggplot() +
  tidyterra::geom_spatraster(data = forest_rast, aes(fill = li)) +
  scale_fill_viridis_c(name = "Li", breaks = seq(4, 9, 1)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_right +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) 

zn <- ggplot() +
  tidyterra::geom_spatraster(data = forest_rast, aes(fill = zn)) +
  scale_fill_viridis_c(name = "Zn", breaks = seq(50, 350, 50)) +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_right +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))
```

```{r}
#| fig-width: 12
#| fig-asp: 0.8
#| label: fig-forest_map
#| fig-cap: Kriged map of select colour (*h\**, *c\**, *v\**) and geochemical (Li, Nb, Zn) properties across the forested site.
 
h_col_forest + li + l_col + nb + v_col + zn + 
  plot_layout(ncol = 2) 
```

### Grain size, OM, elevation

```{r}

dem_forest <- ggplot() +
  tidyterra::geom_spatraster(data = forest_rast, aes(fill = elevation)) +
  scale_fill_viridis_c(name = "Elevation", option = "inferno") +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

ssa_forest <- ggplot() +
  tidyterra::geom_spatraster(data = forest_rast, aes(fill = ssa)) +
  scale_fill_viridis_c(name = "SSA") +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_right +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

organic_forest <- ggplot() +
  tidyterra::geom_spatraster(data = forest_rast, aes(fill = organic)) +
  scale_fill_viridis_c(name = "Organic") +
  #geom_sf(data = filter(coords, site == "Agriculture")) +
  theme_minimal(base_size = 12) +
  theme_left +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0))

scale_p_forest <- ggplot() +
  geom_sf(data = filter(coords, site == "Forest"), colour = "white") +
  theme_void(base_size = 12)+
  ggspatial::annotation_scale(location = "bl", width_hint = 0.3) +
  ggspatial::annotation_north_arrow(location = "bl", pad_y  = unit(2, "cm"))

```

```{r}
#| fig-width: 12
#| fig-asp: 0.6
#| label: fig-forest_map2
#| fig-cap: Kriged map of organic matter content (%), specific surface area (m<sup>2</sup> kg<sup>-1</sup>), and elevation (m) across the forested site.

organic_forest + ssa_forest + dem_forest + scale_p_forest + 
  plot_layout(ncol = 2) 
```


